SampleMVCApplication/Models/ErrorViewModel.cs
namespace SampleMVCApplication.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SampleMVCApplication/Models/ProductViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SampleMVCApplication.Custom;

namespace SampleMVCApplication.Models
{
    public class ProductViewModel
    {
        [ScaffoldColumn(false)]
        public int ProductId { get; set; }

        [DisplayName("Product Name")]
        public required string ProductName { get; set; }

        [DisplayName("Product Description")]
        public required string ProductDescription { get; set; }

        [DisplayName("Product Code")]
        [RegularExpression("^[a-zA-Z0-9 ]+$")]
        [CodeValidatorcs(ErrorMessage ="Product Code does not start with P character")]
        public required string ProductCode { get; set; }

        [DisplayName("Product Price")]
        [Range(10, int.MaxValue)]
        public decimal Price { get; set; }
    }
}

SampleMVCApplication/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SampleMVCApplication.Models;

namespace SampleMVCApplication.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SampleMVCApplication/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using SampleMVCApplication.Models;

namespace SampleMVCApplication.Controllers
{
    [Route("product")]
    public class ProductController : Controller
    {
        static List<ProductViewModel> Products = new List<ProductViewModel>() { 
            new ProductViewModel() { ProductId=1001, ProductCode="P001", ProductName="Laptop" , ProductDescription="Laptop", Price=1200 } };
        [Route("GetInfo")]
        public IActionResult GetProductInfo()
        {
            ProductViewModel productViewModel = new ProductViewModel() { Price = 10, ProductCode = "PRD001", ProductId = 1001, ProductDescription = "Sample Product", ProductName = "Sample Product" };
           // ViewData["Product"] = productViewModel;
            return View(productViewModel);
        }

        [Route("Add")]
        [HttpGet]
        public IActionResult Create() { 
            return View("CreateV1");
        }

        [Route("Save")]
        [HttpPost]
        public IActionResult SaveProduct(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                Products.Add(productViewModel);
                //return View();
                return RedirectToAction("ProductList");
            }
            return View("CreateV1");
        }

        [Route("ProductList")]
        [HttpGet]
        public IActionResult ProductList()
        {
            return View("ProductCard",Products);
        }
    }
}

SampleMVCApplication/Custom/DiscountOfferViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SampleMVCApplication.Custom
{
    public class DiscountOfferViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(decimal price)
        {
            if (price > 3000)
            {
                decimal discount = price * 15 / 100;
                decimal finalprice = price - discount;

                return View("_DiscountOffer", finalprice);

            }
            return View("_NoOffer");
        }
    }
}

SampleMVCApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SampleMVCApplication/Views/Product/Create.cshtml
@model ProductViewModel
@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>

@*<form action="Save" method="post">
    <label>Product Id:</label>
    <input type="text" name="ProductId"/>
    <br/>
    <label>Product Code:</label>
    <input type="text" name="ProductCode" />
    <br />
    <label>Product Name:</label>
    <input type="text" name="ProductName" />
    <br />
    <label>Product Description:</label>
    <input type="text" name="ProductDescription" />
    <br />
    <label>Product Price:</label>
    <input type="text" name="Price" />
    <br />
    <input type="Submit" value="Submit"/>
</form>*@

@*using (Html.BeginForm("Save","product",FormMethod.Post))
{ 
    @Html.Label("ProductId");
    @Html.TextBox("ProductId");
    <br/>
    @Html.Label("ProductName");
    @Html.TextBox("ProductName");
    <br/>
    @Html.Label("ProductCode");
    @Html.TextBox("ProductCode");
    <br/>
    @Html.Label("ProductDescription");
    @Html.TextBox("ProductDescription")
    ;
    <br/>
    @Html.Label("Price")
    ;
    @Html.TextBox("Price")
    ;
    <br />
   <input type="Submit" value="Save"/>

}*@

<div class="row">
	<div class="col-lg-6 col-sm-9">
		@using (Html.BeginForm("Save", "product", FormMethod.Post))
		{
			@* <div class="mb-3">
                @Html.LabelFor(x => x.ProductId)
                @Html.TextBoxFor(x => x.ProductId,"", new {@class= "form-control"})
            </div>
            <div class="mb-3">
                @Html.LabelFor(x => x.ProductCode)
                @Html.TextBoxFor(x => x.ProductCode, "", new { @class = "form-control" })
            </div>
            <div class="mb-3">
            @Html.LabelFor(x => x.ProductName)
                @Html.TextBoxFor(x => x.ProductName, "", new { @class = "form-control" })
            </div>
            <div class="mb-3">
                @Html.LabelFor(x => x.ProductDescription)

                @Html.TextBoxFor(x => x.ProductDescription, "", new { @class = "form-control" })
           </div>
            <div class="mb-3">
            @Html.LabelFor(x => x.Price)
                @Html.TextBoxFor(x => x.Price, "", new { @class = "form-control" })
           </div>
            *@
			@Html.EditorForModel()
			<input type="Submit" value="Save" class="btn btn-primary" />
		}
	</div>
	<div class="col-lg-6" style="height:300px;background-color:red;"></div>
</div>

SampleMVCApplication/Views/Product/CreateV1.cshtml
@model ProductViewModel
@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>
<div class="row">
	<div class="col-lg-6">
		<form asp-action="save" asp-controller="product" method="post">
			<div class="mb-3">
				<label asp-for="ProductId"></label>
				<input type="text" asp-for="ProductId" class="form-control" />
				<span asp-validation-for="ProductId" class="text-danger" ></span>
			</div>
			<div class="mb-3">
				<label asp-for="ProductCode"></label>
				<input type="text" asp-for="ProductCode" class="form-control" />
				<span asp-validation-for="ProductCode" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="ProductName"></label>
				<input type="text" asp-for="ProductName" class="form-control" />
				<span asp-validation-for="ProductName" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="ProductDescription"></label>
				<input type="text" asp-for="ProductDescription" class="form-control" />
				<span asp-validation-for="ProductDescription" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="Price"></label>
				<input type="text" asp-for="Price" class="form-control" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>
			<div asp-validation-summary="All" class="text-danger" ></div>
			<input type="submit" class="btn btn-primary" value="Save" />
		</form>
	</div>

</div>

SampleMVCApplication/Views/Product/GetProductInfo.cshtml
@model ProductViewModel;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Product Info</h1>
@{
    // var productViewModel = ViewData["Product"] as ProductViewModel;
  //  var productViewModel = ViewBag.Product;
}

@* <p>Product Id: @productViewModel.ProductId </p>
<p>Product Name: @productViewModel.ProductName </p>
<p>Product Code: @productViewModel.ProductCode </p>
<p>Product Description: @productViewModel.ProductDescription </p>
<p>Product Price: @productViewModel.Price </p> *@

<p>Product Id: @Model.ProductId </p>
<p>Product Name: @Model.ProductName </p>
<p>Product Code: @Model.ProductCode </p>
<p>Product Description: @Model.ProductDescription </p>
<p>Product Price: @Model.Price </p>

SampleMVCApplication/Views/Product/ProductCard.cshtml
@model IEnumerable<ProductViewModel>
@{
    ViewData["Title"] = "ProductList";
}

<h1>ProductList</h1>
<a class="btn btn-dark" asp-action="Add" asp-controller="Product">Add Product</a>
<div class="row">
    @foreach (var product in Model)
    { 
        <div class="col-lg-4">
            <partial name="_ProductList" model="product" />
        </div>
    }

</div>

SampleMVCApplication/Views/Product/ProductList.cshtml
@model IEnumerable<ProductViewModel>
@{
    ViewData["Title"] = "ProductList";
}

<h1>ProductList</h1>
<a class="btn btn-dark" asp-action="Add" asp-controller="Product">Add Product</a>
<table class="table table-hover"> 
    <thead>
        <tr>
            <td>Product Id</td>
            <td>Product Code</td>
            <td>Product Name</td>
            <td>Product Description</td>
            <td>Price</td>
        </tr>
    </thead>
    @foreach (var item in Model)
    { 
        <tr>
            <td>@item.ProductId</td>
             <td>@item.ProductCode</td>
            <td>@item.ProductName</td>
            <td>@item.ProductDescription</td>
            <td>@item.Price</td>
        </tr>
    }
</table>

SampleMVCApplication/Views/Product/Save.cshtml
@{
    ViewData["Title"] = "Save";
}

<h1>Product Added Successfully</h1>

SampleMVCApplication/Views/Shared/Components/DiscountOffer/_DiscountOffer.cshtml
@model decimal
<p class="alert alert-dark">Discounted Price is @Model</p>

SampleMVCApplication/Views/Shared/Components/DiscountOffer/_NoOffer.cshtml
<p class="alert alert-dark">There is no discount</p>

SampleMVCApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleMVCApplication</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SampleMVCApplication.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</head>
<body class="container">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SampleMVCApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SampleMVCApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SampleMVCApplication/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleMVCApplication</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SampleMVCApplication.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</head>
<body class="container">
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-action="Add" asp-controller="Product" >Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  asp-action="ProductList" asp-controller="Product">Product List Card</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <div class="footer text-center alert-warning">Copright @@2024</div>
</body>
</html>

SampleMVCApplication/Views/Shared/_ProductList.cshtml
@model ProductViewModel

<div class="col-lg-4">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.ProductName</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">@Model.ProductDescription</h6>
            <vc:discount-offer price="@Model.Price"></vc:discount-offer>
            <p class="card-text">@Model.Price</p>
            <a href="#" class="card-link">Card link</a>
        </div>
    </div>
    <my-custom message="This is my Tag Helper"></my-custom>
    <my-custom>Vijender,Ravi,Abhiraj,Aryadit</my-custom>
    <custom>Vijender,Ravi,Abhiraj,Aryadit</custom>
</div>